{
 "title": "Herbier1",
 "description": " toutes mesures",
 "time": { "from": "2020-04-13T08:03:27.692Z", "to": "2020-07-05T11:27:41.537Z" },
 "panels": [
  {
   "title": "Puissances appelées empilées & général Transfo",
   "type": "graph",
   "gridPos": { "h": 16, "w": 23, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short", "label": "kW" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"defaultBucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r.device_name != \"GENE TRANSFO\" and\r\n    r.device_name != \"P_3 AGBT\" and\r\n    r.measured_value == \"EA+\" and\r\n    r._field == \"value\"\r\n  )\r\n|> derivative(unit: 1h, nonNegative: false)\r\n"
    },
    {
     "query": "from(bucket: \"defaultBucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r.device_name == \"GENE TRANSFO\" and\r\n    r.measured_value == \"EA+\" and\r\n    r._field == \"value\"\r\n  )\r\n|> derivative(unit: 1h, nonNegative: true)"
    }
   ]
  },
  {
   "title": "Profil appel de puissance par appareil",
   "type": "graph",
   "gridPos": { "h": 16, "w": 23, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "kW" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"defaultBucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r.device_name != \"GENE TRANSFO\" and\r\n    r.device_name != \"P_3 AGBT\" and\r\n    r.measured_value == \"EA+\" and\r\n    r._field == \"value\"\r\n  )\r\n|> derivative(unit: 1h, nonNegative: true)\r\n"
    }
   ]
  },
  {
   "title": "Consommations journalières empilées & général transfo",
   "type": "graph",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "string", "label": "kWh" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"defaultBucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r.measured_value == \"EA+\" and\r\n    r.device_name != \"GENE TRANSFO\" and\r\n    r.device_name != \"P_3 AGBT\"\r\n  )\r\n|> aggregateWindow(every: 1d, fn: max, createEmpty: false)\r\n|> derivative(unit: 1d, nonNegative: true)\r\n|> timeShift(duration: -20h)"
    },
    {
     "query": "from(bucket: \"defaultBucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r.device_name == \"GENE TRANSFO\" and\r\n    r.measured_value == \"EA+\" \r\n  )\r\n|> aggregateWindow(every: 1d, fn: max, createEmpty: false)\r\n|> derivative(unit: 1d, nonNegative: true)\r\n|> timeShift(duration: -20h)"
    }
   ]
  },
  {
   "title": "Répartition de la consommation (kWh/jour)",
   "type": "piechart",
   "gridPos": { "h": 16, "w": 11, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "\r\nfrom(bucket: \"defaultBucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"measured_value\"] == \"EA+\")  \r\n  |> filter(fn: (r) => r[\"device_name\"] != \"GENE TRANSFO\" and r[\"device_name\"] != \"P_3 AGBT\")\r\n  |> aggregateWindow(every: 1d, fn: max, createEmpty: false)\r\n  |> derivative(unit: 1d, nonNegative: false)"
    }
   ]
  },
  {
   "title": "CONT. FROID1 & 2",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short", "label": "kW" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"defaultBucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    (r.device_name == \"CONT. FROID 1\" or r.device_name == \"CONT. FROID 2\") and\r\n    r.measured_value == \"EA+\" and\r\n    r._field == \"value\"\r\n  )\r\n|> aggregateWindow(every: 1h, fn: mean, createEmpty: false)  \r\n|> derivative(unit: 1h, nonNegative: true)"
    }
   ]
  },
  {
   "title": "COUPE 1 & 2",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short", "label": "kW" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"defaultBucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    (r.device_name == \"COUPE 1\" or r.device_name == \"COUPE 2\") and\r\n    r.measured_value == \"EA+\" and\r\n    r._field == \"value\"\r\n  )\r\n|> aggregateWindow(every: 1h, fn: mean, createEmpty: false)\r\n|> derivative(unit: 1h, nonNegative: false)"
    }
   ]
  }
 ]
}